"""Summon template registry for character progression metadata (Pass A)."""
from __future__ import annotations

import copy
from typing import Any


SUMMON_TEMPLATE_REGISTRY: dict[str, dict[str, Any]] = {
    "warlock-chain-imp": {
        "id": "warlock-chain-imp",
        "displayName": "Imp Familiar",
        "summonCategory": "familiar",
        "sourceClassId": "warlock",
        "sourceSubclassId": "",
        "sourceFeatureId": "warlock-pact-boon",
        "variantGroup": "warlock-pact-chain-familiar",
        "actorType": "companion",
        "tokenName": "Imp",
        "size": "tiny",
        "movement": {"walk": 20, "fly": 40},
        "senses": {"darkvision": 120},
        "baseStats": {"scaling": "warlock_familiar_placeholder"},
        "commandModel": "bonus_action_command",
        "maxActive": 1,
        "replaceOnResummon": True,
        "tags": ["warlock", "familiar", "chain"],
    },
    "warlock-chain-pseudodragon": {
        "id": "warlock-chain-pseudodragon",
        "displayName": "Pseudodragon Familiar",
        "summonCategory": "familiar",
        "sourceClassId": "warlock",
        "sourceSubclassId": "",
        "sourceFeatureId": "warlock-pact-boon",
        "variantGroup": "warlock-pact-chain-familiar",
        "actorType": "companion",
        "tokenName": "Pseudodragon",
        "size": "tiny",
        "movement": {"walk": 15, "fly": 60},
        "senses": {"blindsight": 10, "darkvision": 60},
        "baseStats": {"scaling": "warlock_familiar_placeholder"},
        "commandModel": "bonus_action_command",
        "maxActive": 1,
        "replaceOnResummon": True,
        "tags": ["warlock", "familiar", "chain"],
    },
    "warlock-chain-quasit": {
        "id": "warlock-chain-quasit",
        "displayName": "Quasit Familiar",
        "summonCategory": "familiar",
        "sourceClassId": "warlock",
        "sourceSubclassId": "",
        "sourceFeatureId": "warlock-pact-boon",
        "variantGroup": "warlock-pact-chain-familiar",
        "actorType": "companion",
        "tokenName": "Quasit",
        "size": "tiny",
        "movement": {"walk": 40},
        "senses": {"darkvision": 120},
        "baseStats": {"scaling": "warlock_familiar_placeholder"},
        "commandModel": "bonus_action_command",
        "maxActive": 1,
        "replaceOnResummon": True,
        "tags": ["warlock", "familiar", "chain"],
    },
    "warlock-chain-sprite": {
        "id": "warlock-chain-sprite",
        "displayName": "Sprite Familiar",
        "summonCategory": "familiar",
        "sourceClassId": "warlock",
        "sourceSubclassId": "",
        "sourceFeatureId": "warlock-pact-boon",
        "variantGroup": "warlock-pact-chain-familiar",
        "actorType": "companion",
        "tokenName": "Sprite",
        "size": "tiny",
        "movement": {"walk": 10, "fly": 40},
        "senses": {"darkvision": 60},
        "baseStats": {"scaling": "warlock_familiar_placeholder"},
        "commandModel": "bonus_action_command",
        "maxActive": 1,
        "replaceOnResummon": True,
        "tags": ["warlock", "familiar", "chain"],
    },
    "ranger-primal-beast-land": {
        "id": "ranger-primal-beast-land",
        "displayName": "Primal Beast of the Land",
        "summonCategory": "companion",
        "sourceClassId": "ranger",
        "sourceSubclassId": "beast-master",
        "sourceFeatureId": "beast-master-rangers-companion",
        "variantGroup": "ranger-primal-beast",
        "actorType": "companion",
        "tokenName": "Primal Beast (Land)",
        "size": "medium",
        "movement": {"walk": 40, "climb": 40},
        "senses": {"darkvision": 60},
        "baseStats": {"scaling": "ranger_primal_beast_placeholder"},
        "commandModel": "bonus_action_command",
        "maxActive": 1,
        "replaceOnResummon": True,
        "tags": ["ranger", "beast-master", "primal-beast", "land"],
    },
    "ranger-primal-beast-sea": {
        "id": "ranger-primal-beast-sea",
        "displayName": "Primal Beast of the Sea",
        "summonCategory": "companion",
        "sourceClassId": "ranger",
        "sourceSubclassId": "beast-master",
        "sourceFeatureId": "beast-master-rangers-companion",
        "variantGroup": "ranger-primal-beast",
        "actorType": "companion",
        "tokenName": "Primal Beast (Sea)",
        "size": "medium",
        "movement": {"walk": 5, "swim": 60},
        "senses": {"darkvision": 60},
        "baseStats": {"scaling": "ranger_primal_beast_placeholder"},
        "commandModel": "bonus_action_command",
        "maxActive": 1,
        "replaceOnResummon": True,
        "tags": ["ranger", "beast-master", "primal-beast", "sea"],
    },
    "ranger-primal-beast-sky": {
        "id": "ranger-primal-beast-sky",
        "displayName": "Primal Beast of the Sky",
        "summonCategory": "companion",
        "sourceClassId": "ranger",
        "sourceSubclassId": "beast-master",
        "sourceFeatureId": "beast-master-rangers-companion",
        "variantGroup": "ranger-primal-beast",
        "actorType": "companion",
        "tokenName": "Primal Beast (Sky)",
        "size": "small",
        "movement": {"walk": 10, "fly": 60},
        "senses": {"darkvision": 60},
        "baseStats": {"scaling": "ranger_primal_beast_placeholder"},
        "commandModel": "bonus_action_command",
        "maxActive": 1,
        "replaceOnResummon": True,
        "tags": ["ranger", "beast-master", "primal-beast", "sky"],
    },
    "tinker-mechanist-companion-frame": {
        "id": "tinker-mechanist-companion-frame",
        "displayName": "Mechanist Companion Frame",
        "summonCategory": "construct",
        "sourceClassId": "tinker",
        "sourceSubclassId": "mechanist",
        "sourceFeatureId": "mechanist-companion-frame",
        "variantGroup": "tinker-mechanist-frame",
        "actorType": "construct",
        "tokenName": "Companion Frame",
        "size": "medium",
        "movement": {"walk": 30},
        "senses": {"darkvision": 60},
        "baseStats": {"scaling": "tinker_mechanist_frame_placeholder"},
        "commandModel": "bonus_action_command",
        "maxActive": 1,
        "replaceOnResummon": True,
        "tags": ["tinker", "mechanist", "construct", "companion"],
    },
    "tinker-artillerist-arc-cannon": {
        "id": "tinker-artillerist-arc-cannon",
        "displayName": "Arc Cannon",
        "summonCategory": "deployable",
        "sourceClassId": "tinker",
        "sourceSubclassId": "artillerist",
        "sourceFeatureId": "artillerist-arc-cannon",
        "variantGroup": "tinker-artillerist-cannon",
        "actorType": "deployable",
        "tokenName": "Arc Cannon",
        "size": "small",
        "movement": {"walk": 15},
        "senses": {},
        "baseStats": {"scaling": "tinker_arc_cannon_placeholder"},
        "commandModel": "action_command",
        "maxActive": 1,
        "replaceOnResummon": True,
        "tags": ["tinker", "artillerist", "deployable", "cannon"],
    },
    "spell-conjure-fey-manifestation": {
        "id": "spell-conjure-fey-manifestation",
        "displayName": "Conjure Fey Manifestation",
        "summonCategory": "spell_effect",
        "sourceClassId": "spell",
        "sourceSubclassId": "",
        "sourceFeatureId": "spell:conjure-fey",
        "variantGroup": "spell-conjure-fey",
        "actorType": "spell_effect",
        "tokenName": "Conjured Fey",
        "size": "large",
        "movement": {"walk": 30},
        "senses": {},
        "baseStats": {"scaling": "spell_effect_placeholder"},
        "commandModel": "spell_effect",
        "maxActive": 1,
        "replaceOnResummon": True,
        "summonOrigin": "spell",
        "spellId": "conjure-fey",
        "temporary": True,
        "concentrationRequired": True,
        "durationSeconds": 3600,
        "cleanupPolicy": ["dismiss", "duration_expiry", "long_rest", "short_rest", "stale_token"],
        "controlModel": "caster_owned_independent_effect",
        "tags": ["spell", "summon", "temporary", "concentration", "conjuration"],
    },
    "spell-conjure-celestial-manifestation": {
        "id": "spell-conjure-celestial-manifestation",
        "displayName": "Conjure Celestial Manifestation",
        "summonCategory": "spell_effect",
        "sourceClassId": "spell",
        "sourceSubclassId": "",
        "sourceFeatureId": "spell:conjure-celestial",
        "variantGroup": "spell-conjure-celestial",
        "actorType": "spell_effect",
        "tokenName": "Conjured Celestial",
        "size": "large",
        "movement": {"walk": 30, "fly": 60},
        "senses": {"darkvision": 60},
        "baseStats": {"scaling": "spell_effect_placeholder"},
        "commandModel": "spell_effect",
        "maxActive": 1,
        "replaceOnResummon": True,
        "summonOrigin": "spell",
        "spellId": "conjure-celestial",
        "temporary": True,
        "concentrationRequired": True,
        "durationSeconds": 3600,
        "cleanupPolicy": ["dismiss", "duration_expiry", "long_rest", "short_rest", "stale_token"],
        "controlModel": "caster_owned_independent_effect",
        "tags": ["spell", "summon", "temporary", "concentration", "conjuration"],
    },
}


def get_summon_template(template_id: Any) -> dict[str, Any] | None:
    key = str(template_id or "").strip().lower()
    if not key:
        return None
    row = SUMMON_TEMPLATE_REGISTRY.get(key)
    return copy.deepcopy(row) if isinstance(row, dict) else None


def list_summon_templates() -> list[dict[str, Any]]:
    return [copy.deepcopy(row) for row in SUMMON_TEMPLATE_REGISTRY.values() if isinstance(row, dict)]
